# FastMCP Cloud Configuration
# Configuración para deployment automático en FastMCP Cloud

name: trackhs-mcp-connector
version: 1.0.0
description: TrackHS MCP Connector for reservation management

# Configuración del servidor
server:
  name: "TrackHS MCP Server"
  version: "1.0.0"
  description: "MCP Server for TrackHS API integration"
  author: "IHSolutions"
  email: "team@ihsolutions.co"
  
# Configuración de la aplicación
app:
  entry_point: "src.trackhs_mcp.server:main"
  python_version: "3.11"
  requirements:
    - "fastmcp>=2.0.0"
    - "httpx>=0.24.0"
    - "pydantic>=2.0.0"
    - "python-dotenv>=1.0.0"
  
# Variables de entorno requeridas
environment:
  required:
    - TRACKHS_API_URL
    - TRACKHS_USERNAME
    - TRACKHS_PASSWORD
  optional:
    - TRACKHS_TIMEOUT
    - FASTMCP_API_KEY
    
# Configuración de deployment
deployment:
  platform: "fastmcp-cloud"
  region: "us-east-1"
  instance_type: "small"
  auto_scale:
    min_instances: 1
    max_instances: 3
    target_cpu: 70
    
# Configuración de salud
health_check:
  endpoint: "/health"
  interval: 30
  timeout: 10
  retries: 3
  
# Configuración de logging
logging:
  level: "INFO"
  format: "json"
  retention: "30d"
  
# Configuración de monitoreo
monitoring:
  metrics: true
  alerts: true
  dashboard: true
  
# Configuración de seguridad
security:
  https_only: true
  cors_enabled: true
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    
# Configuración de backup
backup:
  enabled: true
  frequency: "daily"
  retention: "7d"
  
# Configuración de notificaciones
notifications:
  email:
    enabled: true
    recipients:
      - "team@ihsolutions.co"
  slack:
    enabled: false
    webhook_url: ""
    
# Configuración de CI/CD
ci_cd:
  auto_deploy: true
  branch: "main"
  tests_required: true
  security_scan: true
  
# Configuración de desarrollo
development:
  debug_mode: false
  hot_reload: false
  local_port: 8000
  
# Configuración de producción
production:
  debug_mode: false
  hot_reload: false
  ssl_enabled: true
  domain: "trackhs-mcp.fastmcp.cloud"
