# Pre-commit hooks optimizados para MCP Protocol MVP
# Enfoque: Calidad alta con validación MCP específica

repos:
  # 1. Hooks básicos esenciales
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Eliminar espacios al final
      - id: check-merge-conflict
        name: Verificar conflictos de merge
      - id: check-yaml
        name: Validar archivos YAML
      - id: check-added-large-files
        name: Prevenir archivos grandes
        args: ['--maxkb=1000']

  # 2. Formateo de código Python (auto-fix)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: Formatear código con Black
        args: [--line-length=88]

  # 3. Ordenamiento de imports (auto-fix)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Ordenar imports con isort
        args: [--profile=black]

  # 4. Tests MCP optimizados (solo tests críticos)
  - repo: local
    hooks:
      - id: pytest-mcp
        name: Tests MCP Protocol
        entry: pytest
        args: [tests/unit/test_simple_refactored.py, -v, --tb=short]
        language: system
        pass_filenames: false
        always_run: false

  # 5. Validación de servidor MCP
  - repo: local
    hooks:
      - id: mcp-server-check
        name: Validar servidor MCP
        entry: python
        args: [-c, "import sys; sys.path.insert(0, 'src'); from server import TrackHSServer; print('MCP Server OK')"]
        language: system
        pass_filenames: false
        always_run: false

# Configuración optimizada para MCP
default_stages: [pre-commit]
fail_fast: true
minimum_pre_commit_version: 3.6.0
