# Pre-commit hooks con tests optimizados para MVP
# Enfoque: Calidad alta con tests rápidos e inteligentes

repos:
  # 1. Hooks básicos esenciales
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Eliminar espacios al final
      - id: check-merge-conflict
        name: Verificar conflictos de merge
      - id: check-yaml
        name: Validar archivos YAML
      - id: check-added-large-files
        name: Prevenir archivos grandes
        args: ['--maxkb=1000']

  # 2. Formateo de código Python (auto-fix)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: Formatear código con Black
        args: [--line-length=88]

  # 3. Ordenamiento de imports (auto-fix)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Ordenar imports con isort
        args: [--profile=black]

  # 4. Linting básico para errores críticos (deshabilitado temporalmente)
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       name: Validar errores críticos Python
  #       args: [--select=E9,F63,F7,F82,--max-line-length=88]
  #       files: ^src/.*\.py$
  #       exclude: ^src/trackhs_mcp/domain/entities/base\.py$

  # 5. Tests se ejecutan en CI, no en pre-commit para mayor velocidad

# Configuración
default_stages: [pre-commit]
fail_fast: true
minimum_pre_commit_version: 3.6.0
