name = "trackhs-mcp-remote"
main = "cloudflare/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ENVIRONMENT = "production" }

# Variables secretas (configurar con wrangler secret put)
# TRACKHS_API_URL
# TRACKHS_USERNAME  
# TRACKHS_PASSWORD
# OAUTH_CLIENT_ID (opcional, por defecto: trackhs-mcp-client)
# OAUTH_CLIENT_SECRET (opcional, por defecto: trackhs-mcp-secret)

[env.development]
vars = { ENVIRONMENT = "development" }
