name: MCP Server CI/CD

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests with coverage
        env:
          TRACKHS_API_URL: "https://ihmvacations.trackhs.com/api"
          TRACKHS_USERNAME: "test_user"
          TRACKHS_PASSWORD: "test_password"
        run: |
          pytest tests/ -v --cov=src --cov-report=term-missing --cov-report=xml --cov-fail-under=80

      - name: Validate MCP Server
        env:
          TRACKHS_API_URL: "https://ihmvacations.trackhs.com/api"
          TRACKHS_USERNAME: "test_user"
          TRACKHS_PASSWORD: "test_password"
        run: |
          python -c "
          import sys
          sys.path.insert(0, 'src')
          from trackhs_mcp.server import mcp
          assert hasattr(mcp, 'run'), 'MCP server missing run method'
          assert hasattr(mcp, 'tool'), 'MCP server missing tool method'
          print('✅ MCP server is valid')
          "

      - name: Run FastMCP Preflight
        env:
          TRACKHS_API_URL: "https://ihmvacations.trackhs.com/api"
          TRACKHS_USERNAME: "test_user"
          TRACKHS_PASSWORD: "test_password"
        run: |
          python scripts/fastmcp_preflight_simple.py

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            coverage.xml
            htmlcov/
            pytest-*.log
          retention-days: 30

      - name: Upload validation logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-logs
          path: |
            *.log
          retention-days: 30
          if-no-files-found: ignore

      - name: Deployment summary
        if: github.ref == 'refs/heads/main'
        run: |
          echo "## ✅ MCP Server Ready for FastMCP Cloud" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Validations Passed:" >> $GITHUB_STEP_SUMMARY
          echo "- Tests: ✅ (80%+ coverage)" >> $GITHUB_STEP_SUMMARY
          echo "- MCP Server: ✅ (valid)" >> $GITHUB_STEP_SUMMARY
          echo "- FastMCP Preflight: ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### FastMCP Cloud Deployment:" >> $GITHUB_STEP_SUMMARY
          echo "FastMCP Cloud will automatically detect this push and deploy." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**No manual action required** - FastMCP Cloud connected via GitHub integration." >> $GITHUB_STEP_SUMMARY
